---

- name: install the latest version of nginx
  apt: pkg=nginx state=latest

- name: remove default nginx config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: deploy nginx config
  template: src=nginx.conf dest=/etc/nginx/sites-enabled/hello.conf
  notify: reload nginx

- name: ensure nginx is running
  service: name=nginx state=started enabled=true
