---

- name: install the latest version of nginx
  apt: pkg=nginx state=latest

- name: deploy nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: ensure nginx is running
  service: name=nginx state=started enabled=true
