---

- name: install apt packages
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - libevent-dev
    - libzmq-dev
    - python-dev
    - python-gevent
    - python-virtualenv

- name: install pip packages
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - circus
    - circus-web
  notify: restart app

- name: install pip packages
  pip: name={{ item }} state=latest
       virtualenv=/var/venv/hello/
  with_items:
    - pip
    - chaussette
    - meinheld
    - 'git+http://gist.github.com/6049805.git#egg=hello'
  notify: restart app

- name: deploy circus config
  copy: src=circus.ini dest=/etc/circus.ini
  notify: restart app

- name: deploy circus upstart config
  copy: src=circus.conf dest=/etc/init/circus.conf
  notify: restart app

- name: ensure app is running
  service: name=circus state=started

# BUG(https://github.com/ansible/ansible/issues/2189): always shows changed
- name: ensure app runs at startup
  service: name=circus enabled=true
