---

- name: install application dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - gunicorn
    - python-gevent
    - python-virtualenv
    - git

- name: fetch application
  git: repo=http://gist.github.com/6049805.git
       dest=/var/www/hello
  notify: reload app

- name: create application config directory
  file: path=/etc/hello/ state=directory mode=0644

- name: deploy gunicorn config
  template: src=gunicorn.conf.py dest=/etc/hello/gunicorn.conf.py
  notify: reload app

- name: deploy upstart config
  copy: src=upstart-hello.conf dest=/etc/init/hello.conf

- name: ensure app is running
  service: name=hello state=started enabled=true
