---

- name: install application dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - supervisor
    - gunicorn
    - python-gevent
    - python-virtualenv
    - git

- name: fetch application
  git: repo=http://gist.github.com/6049805.git
       dest=/var/www/hello
  notify: reload gunicorn

- name: create application config directory
  file: path=/etc/hello/ state=directory mode=0644

- name: deploy gunicorn config for gunicorn
  template: src=gunicorn.conf.py dest=/etc/hello/gunicorn.conf.py
  notify: reload gunicorn

- name: deploy hello supervisor config
  copy: src=supervisor.conf dest=/etc/supervisor/conf.d/hello.conf

- name: ensure supervisor is running
  service: name=supervisor state=started enabled=true

- name: reread supervisor configuration
  command: supervisorctl reread

- name: update supervisor configuration
  command: supervisorctl update

#- name: ensure gunicorn is running
#  supervisorctl: name=gunicorn state=started
